FROM elkbase:jdk-8 
MAINTAINER qinglong siriaodao@vip.qq.com
VOLUME [ "/opt/product/data/" ]
ADD ./elk /opt/product/
ADD ./script/filebeat.sh /root/
RUN chmod +x /root/filebeat.sh
EXPOSE 5601
ENTRYPOINT ["/root/filebeat.sh"]
CMD ["/usr/sbin/init"]
