FROM elkbase:jdk-8 
MAINTAINER qinglong siriaodao@vip.qq.com
VOLUME [ "/opt/product/data/" ]
ADD ./elk /opt/product/
RUN useradd elk && chown -R elk:elk /opt/product/elasticsearch-5.3.0
ADD ./script/elasticsearch.sh /root/
RUN chmod +x /root/elasticsearch.sh
EXPOSE 9200
EXPOSE 9300
ENTRYPOINT ["/root/elasticsearch.sh"]
CMD ["/usr/sbin/init"]
