FROM elkbase:jdk-8 
MAINTAINER qinglong siriaodao@vip.qq.com
VOLUME [ "/opt/product/data/" ]
ADD ./elk/filebeat-5.3.0 /opt/product/filebeat
ADD ./config/filebeat.yml /opt/product/filebeat/filebeat.yml
ADD ./script/filebeat.sh /root/
RUN chmod +x /root/filebeat.sh
ENTRYPOINT ["/root/filebeat.sh"]
CMD ["/usr/sbin/init"]
