FROM elkbase:jdk-8 
MAINTAINER qinglong siriaodao@vip.qq.com
VOLUME [ "/opt/product/data/" ]
ADD ./elk/elasticsearch-5.3.0 /opt/product/elasticsearch
ADD ./config/elasticsearch.yml /opt/product/elasticsearch/config/elasticsearch.yml
RUN useradd elk && chown -R elk:elk /opt/product/elasticsearch
ADD ./script/elasticsearch.sh /root/
RUN chmod +x /root/elasticsearch.sh
EXPOSE 9200
EXPOSE 9300
ENTRYPOINT ["/root/elasticsearch.sh"]
CMD ["/usr/sbin/init"]
