FROM elkbase:jdk-8 
MAINTAINER qinglong siriaodao@vip.qq.com
VOLUME [ "/opt/product/data/" ]
ADD ./elk/logstash-5.3.0 /opt/product/logstash
ADD ./config/logstash.yml /opt/product/logstash/config/logstash.yml
ADD ./config/logstash.conf /opt/product/logstash/config/logstash.conf
ADD ./script/logstash.sh /root/
RUN chmod +x /root/logstash.sh
EXPOSE 5044
EXPOSE 4560
EXPOSE 8080 
ENTRYPOINT ["/root/logstash.sh"]
CMD ["/usr/sbin/init"]
